### ISSUE TITLE
fetching data from mongo seems high latency

### ISSUE THREAD

**Issue by HridoyHazard** [bradtraversy/proshop-v2#16]
after fetching data from mongo using asyncHandler it seems the latency is very high and loading is slow and sometimes get lagged. anyone facing the same issue ??
![image](https://github.com/bradtraversy/proshop-v2/assets/71395891/ca5f8672-2fb4-40bc-9720-438ecb5687d2)
![image](https://github.com/bradtraversy/proshop-v2/assets/71395891/3af77f28-d42d-4236-a7ef-fb1f14ebf5ae)
![image](https://github.com/bradtraversy/proshop-v2/assets/71395891/b1e2ed41-72c7-4cb2-8918-655431f19eb6)

**Comment by bushblade** [comment]
Hi @HridoyHazard 
I guess the bottle neck here would be where your MongoDB is hosted in relation to where you app is running.
For example if your app is running on a server in the UK but your DB is Australasia then yeah it's gonna take a while.
I don't think this would be anything to do with the code here in the repository though and it looks like this is in your own project too?
It looks like you are experiencing this in development locally?
So where is your DB and where are you located in the world?
If you want super fast zero latency then I would recommend running MongoDB locally.
Hope that helps, but I'll close here as an issue with the repository code.
