### ISSUE TITLE
Contribution of Community to Improve This Project

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop-v2#2]
Hello to all of you! I want to say thanks to @bradtraversy  for updating this wonderful and great course / repo. 
It's great to see some improvements to be made but of course, everyone would like to see even more features to make it a full fledged e-commerce site that is great, redundant, and is ultimately safer and has a great UI. Ever since the first course, I have been making small tweaks here, minor tweaks there, and was really expecting for great features such as:

- Better Authentication such as **Auth0** which allows for users to sign in with just a click with Options such as **Google**. I have this option of **Sign In With Google**, with the authentication from this course using passport, but having everything in a very secure and centralized platforms such as Auth0 will be such a great thing to do, especially for something such as an e-commerce store that needs to store sensitive information. Maybe even switching the project to FireBase might even be a better option. Also, things such as Email Verification for Sign Ups, as I've done is something that is missed here.

- Payment before order is placed is crucial to not have orders that will be empty and **not be paid ever**. For this case, I switched from PayPal and I am using Stripe and have moved the placement of screens. Stripe is great and allows for the Payment be done securely

- Using a Shipping API such as Shippo to calculate shipping based on where it is being sent. (I also have this feature in my[ repo](https://github.com/talmax1124/cdshop22), but needs a bit more work, any contributions to my repo would be great).

- Having Options. Many products have variations, so instead of creating new product listing for each variation, this can be done by creating new schemas. This is something that I think we can all work on together as a community

Minor Update could also be updated that can be done fairly easily:
- Reduce Stock once Order Is Placed
- Add Quantity To Cart and Check an API to see if product availability of stock is good.

So, if we can contribute together as devs, I know that we can create an even better version of this already great repository and great. 

Thanks!

---

Below you can see my repository with features such as Email Verification using MailGun, Stripe, Shipping with Shippo API, and other minor improvements. 

https://github.com/talmax1124/cdshop22

**Comment by bushblade** [comment]
Hi @talmax1124 Sounds like you have some great ideas and changes to your own projects, which I commend you for implementing.
This repository though is very much for the [MERN Stack From Scratch](https://www.traversymedia.com/mern-stack-from-scratch) course as it currently is.
If you are a student  of Brad's then you can submit suggestions for future courses in his Discord server **#suggestions** channel. Perhaps what you are describing would be more suited to more intermediate students with prior experience of the MERN stack.
Unless there is a specific issue with the current code base you're experiencing I'll close here.
