### ISSUE TITLE
Facing issues in data seeder script

### ISSUE THREAD

**Issue by rehan-ankalgi-7t2** [bradtraversy/proshop-v2#23]
Hi Brad, i've been follwing your tutorial lately and it was going pretty well untill i faced this error in `data:import` script for importing data in the database

‼️ ```ValidationError: _id: Cast to ObjectId failed for value "1" (type string) at path "_id" because of "BSONError", password: Path `password` is required., email: Path `email` is required.```

however the `data:destroy` script works fine 👍🏻.

it'll be glad if you could suggest a fix for this.

thanks!

**Comment by bushblade** [comment]
Hi @rehan-ankalgi-7t2 
Is this in your own project?
I cannot reproduce the issue you describe in this project.
If you are a student of Brads needing assistance then please post in the course Q&A or on Brads Discord server, make sure to include a link to your projects repository.
However your error seems pretty clear.
You are trying to use the string `'1'` as an `ObjectId` which it is not you are also missing required fields.

**Comment by rehan-ankalgi-7t2** [comment]
Hi @bushblade thanks for reminding me about the Q&A for the course 😃, I'll reach out to brad if have any issue and moreover i fixed this particular issue, no worries 👍🏻
