### ISSUE TITLE
Cannot see jwt in Application/Cookies but when download brads repository I can

### ISSUE THREAD

**Issue by KristijanStosic** [bradtraversy/proshop-v2#25]
When I login it goes through, i also see my user in localStorage and redux store, on the backend it also sets cookie and middleware also works, but somehow when i login or register on frontend and i go into Application/Cookies/localhost:3000 I dont see my jwt cookie? Any explanation or fix? ( i am using vite)
![Screenshot_4](https://github.com/bradtraversy/proshop-v2/assets/63325730/a44dc657-cf54-4de2-a47c-8e011611ba3d)
![Screenshot_3](https://github.com/bradtraversy/proshop-v2/assets/63325730/17a12c8b-54ed-41dc-9cce-9ab92982f9fd)
![Screenshot_2](https://github.com/bradtraversy/proshop-v2/assets/63325730/c932c57d-ca4d-40bf-82d4-ba4d52d84b23)
![Screenshot_1](https://github.com/bradtraversy/proshop-v2/assets/63325730/a791be20-75a7-416f-82d9-c6ebdc180244)

**Comment by bushblade** [comment]
Hi @KristijanStosic.
While that is strange (you should indeed see the cookie), this doesn't appear to be an issue with the repository code that I can reproduce.
You mention you are using Vite, so this must be your own project?
I'll close as an issue here in Brads repository as it doesn't seem related to the code here.
If you are a student of Brads then please post in the course Q&A or Brads Discord server.
