### ISSUE TITLE
Table on ProfileScreen component displays a browser console warning

### ISSUE THREAD

**Issue by anthonypz** [bradtraversy/proshop-v2#4]
The following warning is displayed when loading the bootstrap table for the `ProfileScreen.jsx` component: 
`warning: Received 'true' for a non-boolean attribute table.`
https://github.com/bradtraversy/proshop-v2/blob/98a55bdf77c1c222c530a73dcf017a022d4775d4/frontend/src/screens/ProfileScreen.jsx#L114

According to the react bootstrap [table api](https://react-bootstrap.github.io/docs/components/table/#api), the 'table' attribute is not needed and is set by default. Removing the table attribute clears the warning.

Also, I found a small typo in the same file where the `<tD></tD>` tag should be `<td></td>`.
https://github.com/bradtraversy/proshop-v2/blob/98a55bdf77c1c222c530a73dcf017a022d4775d4/frontend/src/screens/ProfileScreen.jsx#L128

**Comment by anthonypz** [comment]
![Screenshot from 2023-06-04 23-15-31](https://github.com/bradtraversy/proshop-v2/assets/43166263/f7f04593-5fff-41f7-afe9-46a91e6a6f69)

**Comment by bushblade** [comment]
Hey @anthonypz thanks for this, just merged.
