### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by M-Hamza-1** [bradtraversy/proshop-v2#44]
Proxy error: Could not proxy request /api/products? from localhost:3000 to http://localhost:5000/.
[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

pls i need your help. i keep seeing this every time i run the app. what should i do?
the proxy field in package.json is the same as the port . and i added / at the end of the url in the proxy field. and tried to change local host with 127.0.0.1 also didnt work . what should i do ?

**Comment by krishna-cmd** [comment]
I've also facing the same issue.

**Comment by Syed-Bilal-Haider-Engineer** [comment]
Please assign me @M-Hamza-1 
https://github.com/bradtraversy/proshop-v2/pull/45
I resolved the proxy error. please review and approve it. thanks
