### ISSUE TITLE
jwt token not sent to browser's cookie.

### ISSUE THREAD

**Issue by Iftee97** [bradtraversy/proshop-v2#8]
when frontend is deployed, the browser doesn't receive the jwt cookie sent to the browser on login and register. works perfectly the way it should when running locally.

**Comment by bushblade** [comment]
Hi @Iftee97 
Is this in your own project or using the code in this repository?
Where are you deploying to?
Are the frontend and backend served from the same origin?
I you are one of Brads students of the course, could you please ask over on Brad's Discord server or in the course Q&A?

**Comment by bushblade** [comment]
Closing as not enough information and not able to reproduce in repository code.
